### ISSUE TITLE
There are problems with the highlighting of single quotes.

### ISSUE THREAD

**Issue by teo-tsirpanis** [lunet-io/scriban-vscode#3]
![image](https://user-images.githubusercontent.com/12659251/56853225-688c9800-692d-11e9-8309-c9e7ac8d05e6.png)

**Comment by xoofx** [comment]
Sorry, I was not getting notifications for this repo. Don't have time to look into the problem so PR welcome if you find a solution.

**Comment by xoofx** [comment]
Closing as you were probably using `Scriban` script file mode in vscode instead of `Scriban Text`
