### ISSUE TITLE
Add support for plain .html files

### ISSUE THREAD

**Issue by lloydjatkinson** [lunet-io/scriban-vscode#4]

**Comment by xoofx** [comment]
Sorry, not sure to follow, but if you mean syntax highlighing html files without a scriban extension, that can't be done with vscode.

**Comment by lloydjatkinson** [comment]
I meant allow users to use Scriban with HTML files without needing the scriban file extension 🙂

**Comment by xoofx** [comment]
> I meant allow users to use Scriban with HTML files without needing the scriban file extension 🙂

There is no way to detect that with vscode. Another templating engine could use the same `{{`. How would that work?

You can only force the type of file by selecting it yourself (`Scriban-Html`, `CTRL+K m` on Windows)
