### ISSUE TITLE
Scriban for Visual Studio 2019

### ISSUE THREAD

**Issue by abraham-ando** [lunet-io/scriban-vscode#7]
Hi @xoofx,
Thank you for the beautiful library ** Scriban **

If possible, can you have an extension for Visual Studio 2019?

Excuse me for my bad english.

Thank you

**Comment by xoofx** [comment]
Unfortunately, Visual Studio is a lot more involving to create an extension so it won't be possible. I have already maintained in the past a few Visual Studio extensions and it was a pain, so I won't do it for Scriban.
